[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=directory
ImageId=container-debian-13-base
ImageVersion=0.1

[Build]
Environment=
    KERNEL_INSTALL_BYPASS=0

[Content]
Bootable=no
WithDocs=True
Packages=
	apt
	dpkg
        mount
	iproute2
	iputils-ping
	zstd