[Distribution]
Distribution=debian
Release=bookworm

[Match]
Architecture=arm64

[Output]
Format=directory
ImageId=container-debian-12-base
ImageVersion=0.1

[Build]
Environment=
    KERNEL_INSTALL_BYPASS=0

[Content]
Hostname=my-container
Bootable=no
WithDocs=False
Packages=
        apt
        dpkg
        locales
	ntpdate
	curl
	wget
	mtr-tiny
        procps
	iproute2
	iputils-ping
	zstd